---
# handlers for ansible-role-systemd-networkd

- name: restart systemd-networkd
  service:
    name: systemd-networkd
    state: restarted
  when: systemd_networkd_apply_config

- name: check reboot
  set_fact:
    need_reboot: true
  when: not systemd_networkd_apply_config
